### ISSUE TITLE
有个小bug

### ISSUE THREAD

**Issue by yonh** [vicalloy/outline-docker-compose#1]
一键启动的时候生成的容器名称不匹配

![image](https://user-images.githubusercontent.com/10112900/154436537-5bb3c681-8b70-4ae3-ab80-f50127b62c5c.png)

**Comment by vicalloy** [comment]
你的系统环境和docker和docker-compose的版本是什么？
我用的ubuntu系统，名称是对的。
如果不同环境下名称会不一样，我就把容器名称写到配置文件里了。

**Comment by S4kur4** [comment]
我也发现了，可以手动在makefile里改成自动生成的就行了。

**Comment by S4kur4** [comment]
> 你的系统环境和docker和docker-compose的版本是什么？ 我用的ubuntu系统，名称是对的。 如果不同环境下名称会不一样，我就把容器名称写到配置文件里了。

Hi，我刚刚部署成功了，但是登录就会提示认证失败。我检查了client还有账号配置都没问题。
![image](https://user-images.githubusercontent.com/17521941/154437806-a7695601-e359-4052-b19e-058c74761ffe.png)
求助，可能是哪里的问题呢。

**Comment by yonh** [comment]
> 你的系统环境和docker和docker-compose的版本是什么？ 我用的ubuntu系统，名称是对的。 如果不同环境下名称会不一样，我就把容器名称写到配置文件里了。

我发现另一个环境（mac)是正常的
**异常的环境：**
Ubuntu20.04
Linux test 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Docker Compose version v2.2.2
Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2

**Comment by yonh** [comment]
> 我检查了client还有账号配置都没问题。

试下跑make init-uc,然后后台登录，我这样操作是正常能登录的

**Comment by vicalloy** [comment]
@S4kur4 `docker-compose logs wk-outline` 看一下outline的日志是什么。
下面几个问题可以检查一下
1. URL里域名不能是localhost，要用本机IP。用localhost，outline的容器会连不上oidc服务器。
2. 如果修改过 `DEFAULT_LANGUAGE` ，要确定参数正确，如果设置错误也会登录不进去。

@yonh 容器名称错误时，生成的名称是怎么样的？

**Comment by yonh** [comment]
> 

图片上有了 outline-docker-compose_wk-oidc-server_1

**Comment by yonh** [comment]
> @S4kur4 `docker-compose logs wk-outline` 看一下outline的日志是什么。 下面几个问题可以检查一下
> 
> 1. URL里域名不能是localhost，要用本机IP。用localhost，outline的容器会连不上oidc服务器。
> 2. 如果修改过 `DEFAULT_LANGUAGE` ，要确定参数正确，如果设置错误也会登录不进去。
> 
> @yonh 容器名称错误时，生成的名称是怎么样的？

破案了，是因为docker-compose版本不一致，生成的容器名称间隔不一样，1.x版以下划线为间隔，2.x以中划线
![image](https://user-images.githubusercontent.com/10112900/154447160-eab56654-489c-4718-8987-a9988f137003.png)

**Comment by vicalloy** [comment]
恩，2.0以后为了保证容器名符合域名校验规则，将下划线改成减号了。
现在改为使用使用 `docker-compose exec` ，这个问题应当修复了。
