### ISSUE TITLE
请问PG 日志ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted

### ISSUE THREAD

**Issue by mutianqi** [vicalloy/outline-docker-compose#10]
请问ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted 这个应该怎么处理, 手动新建目录吗

**Comment by vicalloy** [comment]
似乎和docker版本有关系，可以参考一下下面两个链接。
https://github.com/docker-library/postgres/issues/890
https://stackoverflow.com/questions/69706677/cannot-start-postgresql-docker-container-docker-entrypoint-initdb-d-oper
