### ISSUE TITLE
Minio/mc is not started

### ISSUE THREAD

**Issue by godima** [vicalloy/outline-docker-compose#11]
Hello!
Thank you for your script, but when I'm trying to start it, all containers is running except one: Minio/mc
Logs contains the following information:
     
Added `minio` successfully.
Bucket created successfully `minio/outline-bucket`.
Access permission for `minio/outline-bucket` is set to `download`
Added `minio` successfully.
mc: <ERROR> Unable to make bucket `minio/outline-bucket`. Your previous request to create the named bucket succeeded and you already own it.
Access permission for `minio/outline-bucket` is set to `download`

Could you help me with that issue?

**Comment by alexdelprete** [comment]
Hi,

I just installed this and had the same doubt, but if you look at docker-compose.yml file, this container is only needed to run a command then exit, to initialize the bucket. So after the command the container gets stopped, it is ok.

I have outline running fine, the only thing I had to change was HTTP_IP, with 127.0.0.1 it was not reachable, I had to put 0.0.0.0 (any) to be able to reach it.

Another issue is that the DATABASE_URL contains user:pass as default, in config.sh I saw no variables to customize that.

But it is up and running...@vicalloy made a great work. :)
