### ISSUE TITLE
请问make install以后访问http://127.0.0.1:8888/ 页面502怎么解决

### ISSUE THREAD

**Issue by WilliamRyan** [vicalloy/outline-docker-compose#12]
请问make install以后访问http://127.0.0.1:8888/ 页面502怎么解决。
访问http://127.0.0.1:8888/uc/admin/auth/user/是正常的

**Comment by vicalloy** [comment]
502是outline没有启动起来。你可以用docker命令看一下outline的日志，看出错原因是什么。

**Comment by vicalloy** [comment]
outline没有提供arm的镜像，如果使用arm平台，需要自己构建outline的镜像。

**Comment by WilliamRyan** [comment]
使用的是interl平台。
从启动的模块看wk-minio和wk-createbulkets有冲突。

mc: <ERROR> Unable to make bucket `minio/outline-bucket`. Your previous request to create the named bucket succeeded and you already own it.

**Comment by vicalloy** [comment]
wk-createbulkets 是用来创建bucket用的，执行完退出。如果bucket已存在就会出现上面的提示，这个是正常的。

**Comment by UriasUdall** [comment]
502的原因应该是nginx路由没有及时刷新，导致no route to host，可以使用命令 docker exec <your outline_wk-nginx container id> nginx -s reload，刷新nginx配置后，就可以正常加载了，或许作者可以修改一下脚本，让nginx启动延时一会儿，就可以解决这个问题了

**Comment by cgerx** [comment]
@UriasUdall 提到的方案完美解决了问题，感谢

**Comment by vicalloy** [comment]
已增加自动nginx reload处理
