### ISSUE TITLE
Outline 0.64.0 环境变量修改导致错误

### ISSUE THREAD

**Issue by vaxl029** [vicalloy/outline-docker-compose#16]
您好，Outline 0.64.0有修改环境变量，outline容器无法正常运行，如果您有空可以更新下就好了，目前跑0.63.0是正常的，感谢
https://github.com/outline/outline/releases/tag/v0.64.0

**Comment by firer1946** [comment]
我用的0.64.3, 在模板文件 `scripts/templates/env.outline` 中添加如下变量就可以了
```
SLACK_CLIENT_ID=xxxx
SLACK_CLIENT_SECRET=xxxxx
```

(用docker logs 查看可以看到没有相关变量的报错)

**Comment by vaxl029** [comment]
> 我用的0.64.3, 在模板文件 `scripts/templates/env.outline` 中添加如下变量就可以了
> 
> ```
> SLACK_CLIENT_ID=xxxx
> SLACK_CLIENT_SECRET=xxxxx
> ```
> 
> (用docker logs 查看可以看到没有相关变量的报错)

感谢指点，已经用上0.64.3
