### ISSUE TITLE
运行安装命令后无法启动，outline-docker-compose-wk-outline-1无限重启

### ISSUE THREAD

**Issue by daidaiwuyifan** [vicalloy/outline-docker-compose#17]
操作系统：Debian11
Docker版本：20.10.16
docker-compose版本：v2.5.0
按照安装命令执行git clone .. cp..  make install
容器outline-docker-compose-wk-outline-1无限重启
日志如下：
== 20220419052832-create-team-domains: migrating =======
== 20220419052832-create-team-domains: migrated (0.015s)

== 20220421052253-create-file-operation-format: migrating =======
== 20220421052253-create-file-operation-format: migrated (0.006s)

== 20220430043135-collection-sort-backfill: migrating =======
Backfilling collection sort…
== 20220430043135-collection-sort-backfill: migrated (0.007s)

Done in 3.89s.
yarn run v1.22.18
$ node ./build/server/index.js
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"level":"warn","message":"Environment configuration is invalid, please check the following:\n\n"}
{"level":"warn","message":"- SLACK_VERIFICATION_TOKEN cannot be used without SLACK_CLIENT_ID."}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.18
$ sequelize db:migrate --env production-ssl-disabled

Sequelize CLI [Node: 16.14.2, CLI: 6.3.0, ORM: 6.9.0]

Loaded configuration file "server/config/database.json".
Using environment "production-ssl-disabled".
No migrations were executed, database schema was already up to date.
Done in 1.01s.
yarn run v1.22.18
$ node ./build/server/index.js
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"level":"warn","message":"Environment configuration is invalid, please check the following:\n\n"}
{"level":"warn","message":"- SLACK_VERIFICATION_TOKEN cannot be used without SLACK_CLIENT_ID."}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.18
$ sequelize db:migrate --env production-ssl-disabled

Sequelize CLI [Node: 16.14.2, CLI: 6.3.0, ORM: 6.9.0]

更换其他vps执行相同步骤，也是同样的问题。
未修改config.sh中的内容，输入邮箱和密码也都正常。

**Comment by firer1946** [comment]
[SLACK_CLIENT_ID](https://github.com/vicalloy/outline-docker-compose/issues/16#issuecomment-1140632612)
