### ISSUE TITLE
无法继续登录到outline

### ISSUE THREAD

**Issue by bluesecret** [vicalloy/outline-docker-compose#24]
第一次进入页面，输入用户名和密码后，点击accept，然后又重新回到登录页面，点击“使用OpenID继续，没反应（一直在此界面循环）

**Comment by Zeqiang-Lai** [comment]
我也遇到了同样的问题，请问你解决了吗

**Comment by bluesecret** [comment]
> 我也遇到了同样的问题，请问你解决了吗
哎， 没有，没去弄了。

**Comment by bluesecret** [comment]
> 我也遇到了同样的问题，请问你解决了吗

还没解决，没去弄了

**Comment by bluesecret** [comment]
> 我昨天后面找到了一个workaround，把outline的版本改低一点就行了，
> 
> https://github.com/vicalloy/outline-docker-compose/blob/b0f35eb7185197efe39f9911c78b3d9c577a81ca/scripts/templates/docker-compose.yml#L46
> 
> 改成 image: outlinewiki/outline:0.64.3

thank

**Comment by wanlinruo** [comment]
我也遇到过这个问题，但我这边是因为未填写邮箱导致的，后面的小伙伴可以留意一下
