### ISSUE TITLE
我在无论是使用下载页面还是导出功能都无法下载图片，单独点击图片却可以下载

### ISSUE THREAD

**Issue by ngu1733** [vicalloy/outline-docker-compose#26]
下载到本地的md文件图片显示如图，并无本地图片文件
![image](https://user-images.githubusercontent.com/52950499/183845066-ba6e6d51-fd17-4648-baa0-7f7068d06c3b.png)
请问我怎样调整可以将图片与文件一起下载下来使用类似typora来打开

**Comment by vicalloy** [comment]
Outline应当不支持连同图片一同导出，具体得看Outline的文档。
