### ISSUE TITLE
登录后无法退出登录

### ISSUE THREAD

**Issue by chen-coco** [vicalloy/outline-docker-compose#30]
在同一浏览器中首次登录账号后，即便退出登录，下次点击”使用OpenID继续“仍然是首次登录账号

无法切换账号和退出

**Comment by vicalloy** [comment]
outline退出了，但是认证服务器没有退出，下次登录outline的时候转到认证服务器自动登录。
要先退出 https://127.0.0.1/uc/ 再退出outline 。
