### ISSUE TITLE
内网穿透后地址跳转出错

### ISSUE THREAD

**Issue by chen-coco** [vicalloy/outline-docker-compose#31]
outline部署在本地hostA服务器，映射端口IP：8888
开启内网穿透映射到公网IP:8888
打开界面欢迎界面正常，点击登录后就会跳转至hostAip:8888
尝试修改config ..URL=127.0.0.1
但会只有本机可访问。映射后还是指向127.0.0.1：8888

**Comment by jzmini** [comment]
I would appreciate it if you spoke English. The use of Google Translate is inconvenient for readers.

**Comment by jzmini** [comment]
It may be possible to resolve the problem by setting the 127.0.0.1 to the LAN IP, e.g., 192.168.1.x.
