### ISSUE TITLE
REST API 添加用户

### ISSUE THREAD

**Issue by ShenQingchuan** [vicalloy/outline-docker-compose#34]
是否有办法创建 REST API 来添加用户？

**Comment by vicalloy** [comment]
outline本身没有提供用户管理的功能。
现在是自己写了个简单的oidc服务器来做用户认证。
如果要REST API，需要修改 https://github.com/vicalloy/oidc-server 这个项目。
如果有用API添加用户的需求，建议使用其他认证后端。
