### ISSUE TITLE
every time start docker makes new volumn 

### ISSUE THREAD

**Issue by bacinchel** [vicalloy/outline-docker-compose#35]
First, thank you for share your standalone docker configuration,

It is very useful for me

even though, I have a humble question.

whenever I restart docker-compose.yml

It creates new docker volumn

below two container always makes new volumn
- outline-docker-compose-wk-redis-1
- outline-docker-compose-wk-minio-1

volumn name looks like ramdom hash number
- 9876d28fa462ad9b7b5bd76a88407a277560314ce32bcd6535cca9744034ddd2
- 61728a2bb2cf9c570487082699bb327c9ab84285b1df4d0eb161e309f26c04cb

I tried figured it out but it was difficult to find out.

If you have some time for look into, please help me. 

thanks

**Comment by jzmini** [comment]
As long as the persistent data is not stored in the volume, I don't think it is critical.
