### ISSUE TITLE
使用bt通过Docker部署时，有一个容器一直启动不了

### ISSUE THREAD

**Issue by CREEPERDCH** [vicalloy/outline-docker-compose#37]
请教一下，问题出现的原因，以及该怎么解决呢
出现问题的容器：outline-docker-compose-wk-createbuckets-1
日志截图：
![](https://wwwwyn4240.oss-cn-shenzhen.aliyuncs.com/fxxking_life/outline.png)

**Comment by CREEPERDCH** [comment]
虽然一直处于stopped状态，但使用过程中似乎没有遇到问题

**Comment by vicalloy** [comment]
那个容器是启动时做数据初始化用的，运行完就退出。
停止是正常的。
