### ISSUE TITLE
minIO: 头像无法显示，但文档中图片、附件正常, 提示403 AccessDenied

### ISSUE THREAD

**Issue by Antisunny** [vicalloy/outline-docker-compose#39]
![image](https://user-images.githubusercontent.com/2398514/196687230-30d63e9a-44ec-409e-93c4-bdeeece90730.png)

**Comment by ahozeuhuol** [comment]
修改了一个版本 [ahozeuhuol/outline-docker-compose](https://github.com/ahozeuhuol/outline-docker-compose) 修改了图片不能显示的问题。

如果已经安装了不想再次晴空安装，或者想基于此repo部署，可以通过以下步骤弥补 [vicalloy/outline-docker-compose图片不能显示问题解决](https://ryanmywork.notion.site/vicalloy-outline-docker-compose-c257d1436017425c9fa0a311e39f99bb)

**Comment by Antisunny** [comment]
已经解决，只要把`scripts/templates/docker-compose.yml`中的`mc policy set`改成`mc anonymous set`就可以了。
