### ISSUE TITLE
感谢大佬的辛勤付出~， 请问下能否支持一下群晖呢（群晖没有make）

### ISSUE THREAD

**Issue by Woooosz** [vicalloy/outline-docker-compose#4]
群晖没有make， 能否提供一个可替代的方式绕过make呢？ 如果大佬没有时间的话，也可以帮忙讲讲思路，我自己边学边搞下。。。

**Comment by molezz** [comment]
要进群晖ssh命令行操作吧？

**Comment by Woooosz** [comment]
> 要进群晖ssh命令行操作吧？

是的 ，但是群晖命令行里面 没有 gcc等编译工具，也没有apt yum 这一类的软件源，可以用docker-compose shell等…所以想问一下大佬怎么改出来一个shell 脚本版的。。。（或者其他可执行脚本）

**Comment by vicalloy** [comment]
对群晖不太了解。不过群晖应当是一个标准的linux系统，make之类的工具是可以自己安装的。

**Comment by Woooosz** [comment]
已解决，感谢

**Comment by niaodian** [comment]
> 已解决，感谢

哥，怎么解决的可以介绍一下不？我安装群晖的toolchain发现也是缺make命令，真是醉了
