### ISSUE TITLE
scripts/config配置的端口非8888，都无法访问文档内都无法加载图片，想问下哪里能配minio跟outline端口对接问题

### ISSUE THREAD

**Issue by xiaoyanyuha** [vicalloy/outline-docker-compose#40]
scripts/config配置的端口非8888，都无法访问文档内都无法加载图片，想问下哪里能配minio跟outline端口对接问题

**Comment by Antisunny** [comment]
我知道什么原因了，

是`scripts/templates/docker-compose.yml`中`mc`的命令使用方式已经失效了，`policy set download`根本就没有起作用。

**Comment by Antisunny** [comment]
#39 已提供解决方式，多种；可以关闭了
