### ISSUE TITLE
用户无法注销的问题

### ISSUE THREAD

**Issue by moyuwang110** [vicalloy/outline-docker-compose#48]
当一个用户登录了outline之后 ，选择“退出登录”，下次将不需要进行登录，可以直接进入outline

**Comment by S4kur4** [comment]
> 当一个用户登录了outline之后 ，选择“退出登录”，下次将不需要进行登录，可以直接进入outline

需要登出的话得在点击“Log out”（或“退出登录”）后，再次打开/uc/admin/页面并点击右上角的“LOG OUT”登出OIDC统一认证服务。
不需要登录能直接进入Outline是因为OIDC的凭证没过期。
