### ISSUE TITLE
Login using oidc-server and Magic link emails not working 

### ISSUE THREAD

**Issue by kani** [vicalloy/outline-docker-compose#6]
Thanks for this magical installation script! it works for me on Ubuntu 20.

I have issues with the login, it is keep redirecting the user back to the login screen with this parameter in the url. Not sure how to get this working.  I have a Nginx proxy running on the server to handle this, this is on a brand new box.

I tried to use the magic link feature because of this issue in login but I am not getting any emails, no errors on screen. It says email sent but I did not get any email. Not sure how to troubleshoot this.

I will be ok if one of this feature works magic link or the login using oidc server. 

Thank you!

**Comment by vicalloy** [comment]
Try to remove all data and do reinstall.
```
make clean-data
```

This scripts is not support email login.
If you want use email, you should add `Emails configuration` in `env.outline`.
```
# Emails configuration (optional)
SMTP_HOST=
SMTP_PORT=
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_FROM_EMAIL=
SMTP_REPLY_EMAIL=
```

**Comment by kani** [comment]
I tried few more times and I noticed.

Users created using `make init-uc` works fine
Users created using the web console /uc/admin  (not taking user to the outline app)  is redirecting to the outline main login page  (see below) after successful login. 

Please let me know if there any logs I can provide to fix this issue.  Thanks! 

<img width="618" alt="image" src="https://user-images.githubusercontent.com/163713/155400921-4aae40b1-aee3-4717-b241-296453647bbc.png">

**Comment by vicalloy** [comment]
You should add email for the new user, and the domain in the email should same as admin user's domain.

**Comment by kani** [comment]
It works now, thank you!  

Is there a setting to turn this requirement off? It will be helpful if we can use some external emails as well.

**Comment by vicalloy** [comment]
It's outline's setting. I didn't find a setting to turn this off.
