### ISSUE TITLE
failed to export all files 导出所有文件失败

### ISSUE THREAD

**Issue by utada1stlove** [vicalloy/outline-docker-compose#71]
环境
|REPOSITORY |TAG |
|:-:|:-:|
|outlinewiki/outline|0.72.0-3|
|postgres|15.2-alpine3.17|
|储存方式|local|

点击导出文件后，出现了下载指示，但点击下载出现404提示 如此[issue#69](https://github.com/vicalloy/outline-docker-compose/issues/69)
配置文件中也存在此参数
```
修改env.outline文件中参数值，单位为Byte：
AWS_S3_UPLOAD_MAX_SIZE=102400000
env.outline文件中添加参数，单位为Byte：
MAXIMUM_IMPORT_SIZE=102400000
```

**Comment by wangweitung** [comment]
> 环境
> REPOSITORY 	TAG
> outlinewiki/outline 	0.72.0-3
> postgres 	15.2-alpine3.17
> 储存方式 	local
> 
> 点击导出文件后，出现了下载指示，但点击下载出现404提示 如此[issue#69](https://github.com/vicalloy/outline-docker-compose/issues/69) 配置文件中也存在此参数
> 
> ```
> 修改env.outline文件中参数值，单位为Byte：
> AWS_S3_UPLOAD_MAX_SIZE=102400000
> env.outline文件中添加参数，单位为Byte：
> MAXIMUM_IMPORT_SIZE=102400000
> ```

you should upate outline to 0.72.2

**Comment by utada1stlove** [comment]
thx,it's my bad.

**Comment by wangweitung** [comment]
> thx,it's my bad.

You can try export from 0.72.2, then import to 0.73.0 .
I always get error upload failed...

**Comment by utada1stlove** [comment]
Thank you for your experience.
