### ISSUE TITLE
Reverse Proxy on Cloudflare?

### ISSUE THREAD

**Issue by MadMaximusJB** [vicalloy/outline-docker-compose#84]
Hello,

I am running into an issue when trying to reverse proxy the site on cloudflare. I set the proxy at port 8888, but the screen when pulled up on any other device at the proxy url just shows "Outline" for the tab title and a blank grey screen. What might be causing this? I've tried changing the "env.outline" URL field to the proxy url, but then it wouldn't even connect to the proxy at all. Any ideas?

Thanks.

**Comment by bolavefasfas** [comment]
Same is hapenning with me I am able to get it working on vps ip and port but not on a domain

**Comment by MadMaximusJB** [comment]
So apparently you just change like all the URLS that are set to "127.0.0.1" to your public domain. The config file, the env file, etc. Go through like every one. And then tinker a bit. Honestly, I don't remember what I did, I just fucked around until it worked.
